/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flowerorderingsystem;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Evel
 */
public class TodaysPickup extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String host = "jdbc:derby://localhost:1527/FlowerOrdering";
    String uName="admindb";
    String uPass="admindb";
    /**
     * Creates new form TodaysPickup
     */
    public TodaysPickup() throws SQLException {
        initComponents();
        Connection con = DriverManager.getConnection(host,uName,uPass);
        updateTable();
    }
    
    private void updateTable(){
        
        try {
            String sql = "SELECT * FROM ORDERS";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FlowerOrderingPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("FlowerOrderingPU").createEntityManager();
        ordersQuery = java.beans.Beans.isDesignTime() ? null : FlowerOrderingPUEntityManager.createQuery("SELECT o FROM Orders o");
        ordersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ordersQuery.getResultList();
        ordersQuery1 = java.beans.Beans.isDesignTime() ? null : FlowerOrderingPUEntityManager.createQuery("SELECT o FROM Orders o");
        ordersList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ordersQuery1.getResultList();
        ordersQuery2 = java.beans.Beans.isDesignTime() ? null : FlowerOrderingPUEntityManager.createQuery("SELECT o FROM Orders o");
        ordersList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ordersQuery2.getResultList();
        ordersQuery3 = java.beans.Beans.isDesignTime() ? null : FlowerOrderingPUEntityManager.createQuery("SELECT o FROM Orders o");
        ordersList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : ordersQuery3.getResultList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Order Description", "CustomerID", "Pickup Date", "Total Amount"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TodaysPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TodaysPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TodaysPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodaysPickup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TodaysPickup().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TodaysPickup.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager FlowerOrderingPUEntityManager;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private java.util.List<flowerorderingsystem.Orders> ordersList;
    private java.util.List<flowerorderingsystem.Orders> ordersList1;
    private java.util.List<flowerorderingsystem.Orders> ordersList2;
    private java.util.List<flowerorderingsystem.Orders> ordersList3;
    private javax.persistence.Query ordersQuery;
    private javax.persistence.Query ordersQuery1;
    private javax.persistence.Query ordersQuery2;
    private javax.persistence.Query ordersQuery3;
    // End of variables declaration//GEN-END:variables
}
